version: '3'

services:
  frontend:
    image: node:18-alpine
    command: yarn dev
    volumes:
       - ./:/app
    working_dir: /app/frontend
    environment:
      - NUXT_PUBLIC_API_ENDPOINT=http://0.0.0.0:1337
      - NUXT_PUBLIC_INTERNAL_API_ENDPOINT=http://strapi:1337
      - NUXT_PUBLIC_USE_S3=false
    depends_on: 
      - strapi
    ports:
      - 3000:3000
      - 24678:24678
    
  strapi:
    image: node:18-alpine
    command: yarn develop
    depends_on:
      - db
    ports:
      - 1337:1337
    volumes:
      - ./:/app
    working_dir: /app/api
  
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data:

